[label_style]
meter=string
fontface=#LabelFont#
fontcolor=0,0,0
fontsize=26
antialias=1
stringalign=right
transformationmatrix=1;-0.06;0;1;0;0
dynamicvariables=1

[value_style]
meter=string
fontface=#NumberFont#
fontcolor=0,0,0
fontsize=26
antialias=1
stringalign=right
x=190
transformationmatrix=1;-0.06;0;1;0;0
dynamicvariables=1

[value_zero_style]
meter=string
fontface=#NumberFont#
fontcolor=0,0,0,40
fontsize=26
antialias=1
stringalign=right
x=190
transformationmatrix=1;-0.06;0;1;0;0
dynamicvariables=1

[bar_style]
meter=string
MyFillColor=fill color 255,255,255
transformationmatrix=1;-0.06;0;1;0;0
dynamicvariables=1