[Variables]

; CPU 0
HWiNFO-CPU0-SensorId=0xF0000300
HWiNFO-CPU0-SensorInstance=0x0
HWiNFO-CPU0-Usage=0x7000009

; CPU 0 DTS
HWiNFO-CPU0-DTS-SensorId=0xF0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
HWiNFO-CPU0-DTS-CoreMax=0x100007f

; Motherboard
HWiNFO-MOBO-SensorId=0xf001889a
HWiNFO-MOBO-SensorInstance=0x1
HWiNFO-MOBO-CPU-Fan=0x3000000

; GPU 0
HWiNFO-GPU0-SensorId=0xe0001800
;0xe0002000
HWiNFO-GPU0-SensorInstance=0x20
;0x0
HWiNFO-GPU0-Usage=0x7000000
HWiNFO-GPU0-Temp=0x1000000
HWiNFO-GPU0-Fan=0x8000000

; GPU 1
HWiNFO-GPU1-SensorId=0xe0002000
HWiNFO-GPU1-SensorInstance=0x14
HWiNFO-GPU1-Usage=0x7000000
HWiNFO-GPU1-Temp=0x1000000
HWiNFO-GPU1-Fan=0x8000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Remote Host 0
HWiNFO-RemoteHost0=0
HWiNFO-RemoteHost0-System-SensorId=0xf0000301
HWiNFO-RemoteHost0-System-SensorInstance=0x0

; Remote Host 0 : CPU 0
HWiNFO-RemoteHost0-CPU0-SensorId=0xF0000300
HWiNFO-RemoteHost0-CPU0-SensorInstance=0x1
HWiNFO-RemoteHost0-CPU0-Usage=0x7000009

; Remote Host 0 : CPU 0 DTS
HWiNFO-RemoteHost0-CPU0-DTS-SensorId=0xF0000400
HWiNFO-RemoteHost0-CPU0-DTS-SensorInstance=0x2
HWiNFO-RemoteHost0-CPU0-DTS-CoreMax=0x100007f

; Remote Host 0 : Motherboard
HWiNFO-RemoteHost0-MOBO-SensorId=0xf001889a
HWiNFO-RemoteHost0-MOBO-SensorInstance=0x5
HWiNFO-RemoteHost0-MOBO-CPU-Fan=0x3000000

; Remote Host 0 : GPU 0
HWiNFO-RemoteHost0-GPU0-SensorId=0xe0001800
HWiNFO-RemoteHost0-GPU0-SensorInstance=0x8
HWiNFO-RemoteHost0-GPU0-Usage=0x7000000
HWiNFO-RemoteHost0-GPU0-Temp=0x1000000
HWiNFO-RemoteHost0-GPU0-Fan=0x3000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Remote Host 1
HWiNFO-RemoteHost1=1
HWiNFO-RemoteHost1-System-SensorId=0xf0000301
HWiNFO-RemoteHost1-System-SensorInstance=0x0

; Remote Host 1 : CPU 0
HWiNFO-RemoteHost1-CPU0-SensorId=0xF0000300
HWiNFO-RemoteHost1-CPU0-SensorInstance=0x1
HWiNFO-RemoteHost1-CPU0-Usage=0x7000005

; Remote Host 1 : CPU 0 DTS
HWiNFO-RemoteHost1-CPU0-DTS-SensorId=0xF0000400
HWiNFO-RemoteHost1-CPU0-DTS-SensorInstance=0x2
HWiNFO-RemoteHost1-CPU0-DTS-CoreMax=0x100007f

; Remote Host 1 : Motherboard
HWiNFO-RemoteHost1-MOBO-SensorId=0xf7067910
HWiNFO-RemoteHost1-MOBO-SensorInstance=0x6
HWiNFO-RemoteHost1-MOBO-CPU-Fan=0x3000001

; Remote Host 1 : GPU 0
HWiNFO-RemoteHost1-GPU0-SensorId=0xe0002000
HWiNFO-RemoteHost1-GPU0-SensorInstance=0xb
HWiNFO-RemoteHost1-GPU0-Usage=0x7000000
HWiNFO-RemoteHost1-GPU0-Temp=0x1000000
HWiNFO-RemoteHost1-GPU0-Fan=0x8000000