; Settings for NowPlayin (WebNowPlaying)

; Persona 5: Ann at Shibuya Station Desktop
; Author=TingTyphoon
; Version=2.0
; License=Creative Commons BY-NC-SA 4.0

[Variables]
Font=personified ux
Scale=1.0
BoxColor=255,0,0
ProfilePicture="#@#Image\ProfilePictures\Levelup_joker.png"

; ProfilePicture default options 
; (can add custom pictures in the "ProfilePictures" folder)
; 	• Ann_Text_Icon.png
; 	• Futaba_Text_Icon.png
; 	• Goro_Text_Icon.png
; 	• Haru_Text_Icon.png
;	• Levelup_joker.png
;	• Ryuji_Text_Icon.png
;	• Yusuke_Text_Icon.png